# Generated by Django 3.0.7 on 2020-06-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.CharField(max_length=25)),
                ('account', models.CharField(max_length=15)),
                ('isPosted', models.BooleanField(default=False)),
            ],
        ),
    ]
