# Generated by Django 3.0.7 on 2020-06-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetids',
            old_name='likes',
            new_name='tweet_id',
        ),
    ]
