# Generated by Django 3.0.7 on 2020-06-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_auto_20200618_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetids',
            old_name='isPosted',
            new_name='is_posted',
        ),
        migrations.RemoveField(
            model_name='tweetids',
            name='tweet_id',
        ),
        migrations.AddField(
            model_name='tweetids',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweetids',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
